FROM sethvargo/hashicorp-installer:0.1.3 AS installer
RUN /install-hashicorp-tool "envconsul" "0.7.3"

FROM alpine:3.16.0
LABEL maintainer="Funding Circle Engineering <engineering+alpine-envconsul@fundingcircle.com>" \
      name="Alpine Linux 3.10 with envconsul and vault entrypoint" \
      version="1.0.0"

COPY --from=installer /software/envconsul /usr/bin/envconsul

RUN apk --no-cache --no-progress --upgrade add \
 bash \
 ca-certificates \
 curl \
 jq \
 openssh-client \
 openssl \
 tini \
 wget

COPY support/ /tmp/support
RUN cd /tmp/support && ./install.sh && rm -rf /tmp/support/
